### ISSUE TITLE
github actions manually triggered

### ISSUE THREAD

**Issue by dogi** [treehouses/cube#8]
https://github.com/treehouses/cube/blob/4065f5f3f47bcea6d6a82aa4f56879e9e7933442/.github/workflows/build.yml#L5

**Comment by sanmay321** [comment]
@dogi hey I'd like to work on this issue

**Comment by dogi** [comment]
@sanmay321 go for it ...

**Comment by dogi** [comment]
hmm ... waited 2 days ... need this for #11
